on:
  pull_request:

jobs:
  test-apk:
    runs-on: ubuntu-latest
    name: Run diffuse action
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build app
        run: wget https://github.com/appium/appium/blob/906350fd335f9485376214fdd17c7cdb6c9ff26b/sample-code/apps/ApiDemos-debug.apk?raw=true -O sample-apk.apk

      - uses: actions/cache@v2
        name: Download base
        with:
          path: diffuse-source-file
          key: diffuse-${{ github.event.pull_request.base.sha }}

      - id: diffuse
        uses: ./
        with:
          old-file-path: diffuse-source-file
          new-file-path: sample-apk.apk

      - run: echo "${{ steps.diffuse.outputs.diff-raw }}"
        shell: bash
