on:
  push:
    branches:
      - master

jobs:
  test-apk:
    runs-on: ubuntu-latest
    name: Run diffuse action
    steps:
      - uses: actions/checkout@v2

      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Get sample .apk for test purposes
        run: wget https://github.com/appium/appium/blob/906350fd335f9485376214fdd17c7cdb6c9ff26b/sample-code/apps/ApiDemos-debug.apk?raw=true -q -O sample-apk.apk

      - id: diffuse
        uses: ./
        with:
          old-file-path: sample-apk.apk
          new-file-path: sample-apk.apk

      - uses: actions/upload-artifact@v2
        with:
          name: diffuse-output
          path: ${{ steps.diffuse.outputs.diff-file }}
