on:
  pull_request:

jobs:
  test-apk:
    runs-on: ubuntu-latest
    name: Run diffuse action
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Get sample .apk for test purposes
        run: wget https://github.com/appium/appium/blob/906350fd335f9485376214fdd17c7cdb6c9ff26b/sample-code/apps/ApiDemos-debug.apk?raw=true -O sample-apk.apk

      - id: diffuse
        uses: ./
        with:
          old-file-path: sample-apk.apk
          new-file-path: sample-apk.apk
          debug: true

      - uses: peter-evans/find-comment@v1
        id: find_comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: APK diff
      - uses: peter-evans/create-or-update-comment@v1
        if: ${{ steps.diffuse.outputs.text-diff != null || steps.find_comment.outputs.comment-id != null }}
        with:
          body: |
            APK diff:
            ```
            ${{ steps.diffuse.outputs.text-diff }}
            ```
            (if visible the action works as expected)
          edit-mode: replace
          comment-id: ${{ steps.find_comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          token: ${{ secrets.GITHUB_TOKEN }}
